name = "Custom green"
bg = "#000000"
fg = "#00FF00"
border = "Plain"
border_color = "#8800FF"
border_focused_color = "#00FF00"
hl_bg = "#0f0f0f"
solid_bg = "White"
solid_fg = "Black"
success = "Green"
error = "#ff0000"
info = "Green"
warning = "Yellow"

[source.nyaa.categories]
anime_english_translated = "LightMagenta"
anime_non_english_translated = "LightGreen"
anime_raw = "Gray"
anime_music_video = "Magenta"
audio_lossless = "Red"
audio_lossy = "Yellow"
literature_english_translated = "LightGreen"
literature_non_english_translated = "Yellow"
literature_raw = "Gray"
live_english_translated = "Yellow"
live_non_english_translated = "LightCyan"
live_idol_promo_video = "LightYellow"
live_raw = "Gray"
picture_graphics = "LightMagenta"
picture_photos = "Magenta"
software_applications = "Blue"
software_games = "LightBlue"

[source.torrentgalaxy.categories]
all_categories = "White"
movies_4k = "LightMagenta"
movies_bollywood = "Green"
movies_cam = "LightCyan"
movies_hd = "LightBlue"
movies_pack = "Magenta"
movies_sd = "Yellow"
tv_hd = "Green"
tv_sd = "LightCyan"
tv_4k = "LightMagenta"
tv_pack = "Blue"
tv_sports = "LightGreen"
anime = "LightMagenta"
apps_mobile = "LightGreen"
apps_other = "Magenta"
apps_windows = "LightCyan"
audiobooks = "Yellow"
comics = "LightGreen"
ebooks = "Green"
educational = "Yellow"
magazines = "Green"
documentaries = "LightYellow"
games_windows = "LightCyan"
games_other = "Yellow"
music_albums = "Cyan"
music_discography = "Magenta"
music_lossless = "LightBlue"
music_video = "Green"
music_singles = "LightYellow"
audio_other = "LightGreen"
pictures_other = "Green"
training_other = "LightBlue"
other = "Yellow"
xxx_4k = "Red"
xxx_hd = "Red"
xxx_misc = "Red"
xxx_sd = "Red"

[source.sukebei.categories]
art_anime = "Magenta"
art_doujinshi = "LightMagenta"
art_games = "Green"
art_manga = "LightGreen"
art_pictures = "Gray"
real_photos = "Red"
real_videos = "Yellow"
