[[manager.prepend_keymap]]
on   = [ "c", "a" ]
run  = "plugin compress"
desc = "Archive selected files"
[[manager.prepend_keymap]]
on  = "M"
run = "plugin mount"
[[manager.prepend_keymap]]
on  = "<C-n>"
run = 'shell -- dragon -x -i -T "$1"'
[[manager.prepend_keymap]]
on  = "y"
run = [ 'shell -- for path in "$@"; do echo "file://$path"; done | wl-copy -t text/uri-list', "yank" ]
[[manager.prepend_keymap]]
on   = "l"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"
